server {
    # Слушаем на 80 порту внутри контейнера
    listen 80;
    server_name localhost;

    client_max_body_size 512M; # Максимальный Вес
    # Корень сайта - папка, куда мы скопировали билд React
    root /usr/share/nginx/html;
    index index.html;

    # --- ПРАВИЛО №1: Если запрашивают файл, который существует - отдать его ---
    # Это для index.html, main.js, main.css и картинок
    location / {
        try_files $uri $uri/ /index.html;
    }

    # --- ПРАВИЛО №2: Если запрос идет к API - перенаправить на бэкенд ---
    # Это наше прокси-правило. Все запросы на /api/... пойдут на Tomcat
    location /api/ {
        # backend - это имя сервиса нашего бэкенда в docker-compose.yml
        proxy_pass http://backend:8080/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # --- ПРАВИЛО №3: Если это WebSocket - провести апгрейд соединения ---
    # Это критически важно для работы нашей "прямой линии"
    location /notifications {
        proxy_pass http://backend:8080/notifications;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }
}