version: '3.8'

services:
  # Наш фронтенд на Nginx - это точка входа для пользователя
  frontend:
    build:
      context: ./frontend
    ports:
      # Мы открываем порт 8081 наружу, чтобы не конфликтовать с 8080 от бэкенда
      - "8081:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      cache_from:
        - gradle_cache:/home/gradle/.gradle
    ports:
      # Этот порт теперь не обязательно открывать наружу,
      # т.к. с ним общается только Nginx внутри Docker-сети
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/moviedb?stringtype=unspecified
      SPRING_DATASOURCE_USERNAME: movieuser
      SPRING_DATASOURCE_PASSWORD: moviepassword
      SPRING_JPA_DATABASE-PLATFORM: org.eclipse.persistence.platform.database.PostgreSQLPlatform
      SPRING_SERVLET_MULTIPART_MAX-FILE-SIZE: 512MB
      SPRING_SERVLET_MULTIPART_MAX-REQUEST-SIZE: 512MB
      SPRING_DATASOURCE_HIKARI_MAXIMUM-POOL-SIZE: 60
        # Увеличиваем таймаут ожидания соединения (чтобы не падал сразу)
      SPRING_DATASOURCE_HIKARI_CONNECTION-TIMEOUT: 30000
      # ВАЖНО: отключаем автоматическую генерацию схемы от JPA, так как мы управляем ей сами
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate # или none
    depends_on:
      db:
        condition: service_healthy # <--- Ждать, пока healthcheck не пройдет

  # Наша база данных
  db:
    image: postgres:16
    container_name: is-1_db
    environment:
      POSTGRES_DB: moviedb
      POSTGRES_USER: movieuser
      POSTGRES_PASSWORD: moviepassword
    ports:
      - "54321:5432"
    volumes:
      # Важно: путь теперь относительный от docker-compose.yml
      - ./backend/db-init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U movieuser -d moviedb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  gradle_cache: