plugins {
    id 'java'
    id 'org.springframework.boot' version '4.0.0'
    id 'io.spring.dependency-management' version '1.1.7'
    // id 'war'
}

group = 'com.hellcat'
version = '0.0.1-SNAPSHOT'
description = 'backend'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }

    configureEach {
        exclude group: 'org.hibernate.orm', module: 'hibernate-core'
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-rest'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-websocket'
    implementation 'org.springframework.boot:spring-boot-starter-amqp'

    compileOnly 'org.projectlombok:lombok'
    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    developmentOnly 'org.springframework.boot:spring-boot-docker-compose'
    runtimeOnly 'org.postgresql:postgresql'
    annotationProcessor 'org.projectlombok:lombok'

    testImplementation 'org.springframework.boot:spring-boot-starter-data-rest-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testImplementation 'org.springframework.boot:spring-boot-testcontainers'
    testImplementation 'org.testcontainers:testcontainers-junit-jupiter'
    testImplementation 'org.testcontainers:testcontainers-postgresql'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    implementation 'com.alibaba:druid-spring-boot-starter:1.2.27'

    // 2. MinIO (S3 Storage)
    implementation 'io.minio:minio:8.6.0'

    // 3. Caching: Ehcache + Spring Cache
    implementation 'org.springframework.boot:spring-boot-starter-cache:4.0.0'
    implementation 'org.ehcache:ehcache:3.11.1'
    implementation 'javax.cache:cache-api:1.1.0'

    implementation 'org.glassfish.jaxb:jaxb-runtime:4.0.5' // Реализация JAXB
    implementation 'javax.xml.bind:jaxb-api:2.3.1' // API (для совместимости старых либ)

    // Иногда нужен и activation
    implementation 'javax.activation:javax.activation-api:1.2.0'

    // 4. AOP (для логирования кэша)
    implementation 'org.springframework.boot:spring-boot-starter-aop:4.0.0-M1'

    // Подключаем EclipseLink как JPA провайдер
    implementation 'org.eclipse.persistence:eclipselink:5.0.0-B11'

    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'

    implementation 'com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.20.0'
    implementation 'org.glassfish.jaxb:jaxb-runtime:2.3.9'
}

tasks.withType(Jar).configureEach {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.withType(Copy).configureEach {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.named('test') {
    useJUnitPlatform()
}
